-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('UNASSIGNED', 'INTERVIEWEE', 'INTERVIEWER');

-- CreateEnum
CREATE TYPE "BookingStatus" AS ENUM ('SCHEDULED', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "AvailabilityStatus" AS ENUM ('AVAILABLE', 'BOOKED', 'BLOCKED');

-- CreateEnum
CREATE TYPE "PayoutStatus" AS ENUM ('PROCESSING', 'PROCESSED');

-- CreateEnum
CREATE TYPE "InterviewCategory" AS ENUM ('FRONTEND', 'BACKEND', 'FULLSTACK', 'DSA', 'SYSTEM_DESIGN', 'BEHAVIORAL', 'DEVOPS', 'MOBILE');

-- CreateEnum
CREATE TYPE "FeedbackRating" AS ENUM ('POOR', 'AVERAGE', 'GOOD', 'EXCELLENT');

-- CreateEnum
CREATE TYPE "TransactionType" AS ENUM ('CREDIT_PURCHASE', 'BOOKING_DEDUCTION', 'BOOKING_EARNING', 'ADMIN_ADJUSTMENT');
